api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.viewsets import UserViewSet, GroupViewSet, CategoryViewSet, ProductViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet, basename='User')
router.register(r'group', GroupViewSet, basename='Group')
router.register(r'category', CategoryViewSet, basename='Category')
router.register(r'product', ProductViewSet, basename='Product')


urlpatterns = [
    path('', include(router.urls)),
]

cart/urls.py
from django.urls.conf import path
from cart.views import cart_detail, cart_add, cart_remove


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('', include('market.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from market.views import home, products_in_category, item_detail

urlpatterns = [
    path('', home, name='home'),
    path('<slug:category_slug>/', products_in_category, name='category'),
    path('product/<slug:product_slug>/<int:id>/', item_detail, name='item'),
]

cart/models.py
from django.db import models

# Create your models here.

market/models.py
from django.db import models
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    parent = TreeForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='children',
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        max_length=50,
        verbose_name='title',
    )
    slug = models.SlugField(
        verbose_name='slug',
        unique=True,
    )

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return f'{self.title}'


class Product(models.Model):
    title = models.CharField(
        max_length=250,
        verbose_name='Product',
    )
    text = models.TextField(
        verbose_name='Text',
    )
    price = models.DecimalField(
        decimal_places=2,
        verbose_name='Price',
        max_digits=10,
    )
    category = models.ForeignKey(
        'Category',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    img = models.ImageField(
        verbose_name='Picture'
    )
    slug = models.SlugField(
        verbose_name='Slug',
        unique=True,
    )

    def __str__(self):
        return f'{self.title}, {self.price}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField()
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

market/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from market.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update'],
        )
    return redirect('cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')

market/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm


def home(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'market/home.html', context)


def products_in_category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {
        'products': products,
    }
    return render(request, 'market/home.html', context)


def item_detail(request, product_slug, id):
    product = get_object_or_404(Product, slug=product_slug, id=id)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'market/item.html', context)

cart/templates/cart/cart_detail.html
{% extends 'market/base.html' %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}

<div class="page_container">
    <div class="template_cart">
	    <div class="container">
			{% if cart.get_total_quantity == 0 %}
				<h1 class="page_heading" style="padding:30px; text-align: center; margin-top: 7%;">
					Your shopping cart is empty :( <br>
					Please add some products.
				</h1>
				<div style="text-align: center;  margin: 50px; margin-bottom: 12.5%;">
					<form action="{% url 'home' %}" method="GET"  >
						{% csrf_token %}
						<button class="btn btn-outline-dark" type="submit" style="font-size: 40px;">
							Go shopping
						</button>
					</form>
				</div>
			{% else %}
				<h1 class="page_heading" style="padding:30px;">Your Shopping Cart</h1>

				<p class="text-right">
					<a href="{% url 'home' %}" class="button light">Continue shopping</a>
					<a href="#" class="button">Checkout</a>
				</p>
				<table class="table table-bordered cart_items" style="margin-bottom: 2.6%;">
					<thead>
						<tr>
							<th class="column_product" colspan="2">Product</th>
							<th class="column_price">Price</th>
							<th class="column_quantity">Quantity</th>
							<th class="column_total">Total</th>
						</tr>
					</thead>

					<tbody>
						{% for item in cart %}
							{% with product=item.product %}
								<tr>
									<td class="column_product_img">
										<a>
											<img class="card-img-cart" src="{{MEDIA_URL}}{{product.img.url}}" width="10%" alt="..." />
										</a>
									</td>

									<td class="column_product_info">
										<p class="cart_item__name product_name">
											<a>{{ product.title }}</a>
										</p>
										<form action="{% url 'cart_remove' product.id %}" method="POST"  >
											{% csrf_token %}
											<button class="btn btn-outline-dark" type="submit">
												Remove
											</button>
										</form>
									</td>

									<td class="column_price">
										<span class="money">${{ item.price }}</span>
									</td>

									<td class="column_quantity">
										<div class="quantity_box">
											<span class="quantity_up">{{ item.quantity }}</span>
										</div>
									</td>

									<td class="column_total">
										<span class="money">${{ item.total_price }}</span>
									</td>
								</tr>
							{% endwith %}
						{% endfor %}
					</tbody>

					<tfoot>
						<tr>
							<td colspan="5">
								<p class="cart_total">Total price <span class="money">${{ cart.get_total_price }}</span></p>
							</td>
						</tr>
					</tfoot>

				</table>
			{% endif %}
        </div>
    </div>
</div>
{% endblock %}

market/templates/market/base.html
{% load static %}
{% load mptt_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'market/css/styles.css' %}" rel="stylesheet" />

    </head>
    <body>
        <style>

            .cats {
                margin: 25px;
            }
            .bg-dark {
                background: url(/media/bg.jpg);
            }
        </style>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home' %}">
                    Online guitar market
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        {% recursetree category.all %}
                            {% if node.is_leaf_node %}
                                <li class="nav-item dropdown">
                                    <a href="{% url 'category' node.slug %}"
                                       style="text-align: center; padding-left: 25px; padding-right: 25px;" class="nav-link" role="button">
                                        {{ node.title }}
                                    </a>
                                </li>
                            {% else %}
                                <li class="nav-item dropdown">
                                    <a href="{% url 'category' node.slug %}" style="text-align: center; padding-left: 25px; padding-right: 25px;" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ node.title }}
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            {{ children }}
                                        </li>
                                    </ul>
                                </li>
                            {% endif %}
                        {% endrecursetree %}
                    </ul>
                    <form action="{% url 'cart_detail' %}" method="get" class="d-flex" >
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.get_total_quantity }}</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>


        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Guitar universe</h1>
                </div>
            </div>
        </header>
        <!-- Section-->
        {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark" style="  position: relative; bottom: 0; width: 100%;">
            <div class="container"><p class="m-0 text-center text-white">
                Copyright &copy; Tramontana Minsk 2021
            </p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

market/templates/market/home.html
{% extends 'market/base.html' %}

{% block title %}Guitar Universe{% endblock %}

{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for i in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top"
                                 src="{{MEDIA_URL}}{{i.img.url}}"
                                 width="50%" alt="..." />
                            <style>
                                .card-img, .card-img-bottom, .card-img-top {
                                    width: 45%;
                                }
                                img, svg {
                                    margin-left: auto;
                                    margin-right: auto;
                                }
                                .card {
                                    border: None;
                                }
                            </style>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{i.title}}</h5>
                                    <!-- Product price-->
                                    {{i.price}}$
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'item' i.slug i.id %}">
                                    View options
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

market/templates/market/item.html
{% extends 'market/base.html' %}

{% load mptt_tags %}

{% block title %}Guitar Universe{% endblock %}

{% block content %}
    <body>
    <style>
        .cats {
            margin: 25px;
        }
        .bg-dark {
            background: url(/media/bg.jpg);
        }
        .display-5 {
            font-size: calc(1.005rem + 2.1vw);
        }
        .card-img, .card-img-bottom, .card-img-top {
            width: 50%;
        }
        img, svg {
            display: block;
            margin: 0 auto;
        }
        .form-control {
            -moz-appearance: textfield;
        }
            .form-control::-webkit-inner-spin-button {
            display: none;
        }
    </style>
        <!-- Navigation-->

        <!-- Product section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img
                            class="card-img-top mb-5 mb-md-0" src="{{MEDIA_URL}}{{product.img.url}}"
                            alt="..."
                    /></div>
                    <div class="col-md-6">
                        <h1 class="display-5 fw-bolder">{{ product.title }}</h1>
                        <div class="fs-5 mb-5">
                            <span>{{ product.price }}$</span>
                        </div>
                        <p class="lead">{{ product.text }}</p>
                        <div class="d-flex">
                            <form action="{% url 'cart_add' product.id %}" method="post" class="d-flex">
                                <input inputmode="integer" class="form-control text-center me-3" type="number" id="inputQuantity" value="1" style="max-width: 3rem" name="quantity" required="">
                                <input type="hidden" name="update" value="False" id="id_update">
                                {% csrf_token %}
                                <button class="btn btn-outline-dark flex-shrink-0">
                                    <i class="bi-cart-fill me-1"></i>
                                    Add to cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
    </body>
</html>
{% endblock %}